/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.database.MemoryDataBase;
import com.mycompany.outros.Forms;
import com.mycompany.outros.Temporarios;
import com.mycompany.veiculo.Veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author grander.3993
 */
public class CadVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form CadVeiculos
     */
    public CadVeiculos() {
        initComponents();
        jtfChassi.requestFocus();
        setarID();
        jtfId.setEnabled(false);
        verifyDadosTemp();
        
        setLocationRelativeTo(null);
    }
    
    private void setarID(){
        try{
            jtfId.setText(String.valueOf(MemoryDataBase.listaVeiculos.get(MemoryDataBase.listaVeiculos.size() - 1).getId() +1));
        }
        catch(IndexOutOfBoundsException e){
            jtfId.setText("0");
        }
    }
    
    private void cadastrar(String chassi, String marca, String nome, String preco, ArrayList<Veiculo> listaVeiculos){
         try{
            int id;
            try{
                id = listaVeiculos.get(listaVeiculos.size() - 1).getId() +1;
            }
            catch(IndexOutOfBoundsException e){
                id = 0;
            }
            
            listaVeiculos.add(new Veiculo(id, chassi, marca, nome, Double.valueOf(preco)));
            JOptionPane.showMessageDialog(null, "Veículo  " + "'" + jtfNome.getText() + "'" + "  cadastrado com sucesso!");
            jtfChassi.setText("");
            jtfMarca.setText("");
            jtfNome.setText("");
            jtfPreco.setText("");
            }
         catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto!");
        }
    }
    
    public void verifyDadosTemp(){
        if(Temporarios.tempObj != null){
            Veiculo v = (Veiculo) Temporarios.tempObj;
            
            jtfId.setText(String.valueOf(v.getId()));
            jtfChassi.setText(v.getChassi());
            jtfMarca.setText(v.getMarca());
            jtfNome.setText(v.getNome());
            jtfPreco.setText(String.valueOf(v.getPreco()));
            
            btnSave.setText("Alterar");
            btnDelete.setVisible(true);
            btnCancel.setVisible(true);
            setTitle("Alteração de veículo");
        }
        else{
        btnSave.setText("Salvar");
            btnDelete.setVisible(false);
            btnCancel.setVisible(false);
            setTitle("Cadastro de produto");
    }
    }
    
    private void alterar (Veiculo v, String chassi, String marca, String nome, String preco, ArrayList<Veiculo> lista){
        try{
            Veiculo veicAlt =  new Veiculo(v.getId(), chassi, marca, nome, Double.parseDouble(preco));
            
            int i = lista.indexOf(Temporarios.tempObj);
            
            lista.set( i, veicAlt);
            JOptionPane.showMessageDialog(null, "Veiculo " + v.getNome() + " alterado com Sucesso.");
            jtfChassi.setText("");
            jtfMarca.setText("");
            jtfNome.setText("");
            jtfPreco.setText("");
            
            Forms.CadVeiculos.dispose();
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "O preço deve conter um valor numerico");
        }
    }
     
    private void delete (Veiculo v, ArrayList<Veiculo> lista ){
        lista.remove(v);
        JOptionPane.showMessageDialog (null, "produto "  + v.getNome() +  " Excluido com sucesso"  );
         jtfChassi.setText("");
            jtfMarca.setText("");
            jtfNome.setText("");
            jtfPreco.setText("");
            
               Forms.CadVeiculos.dispose();
    }
          
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfChassi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jButton3.setText("Cancelar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículos");

        jLabel1.setText("ID");

        jtfId.setEditable(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Chassi");

        jLabel3.setText("Marca");

        jLabel4.setText("Nome");

        jLabel5.setText("Preço");

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(btnCancel))
            .addComponent(jtfNome)
            .addComponent(jtfChassi)
            .addComponent(jtfMarca)
            .addComponent(jtfPreco)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Forms.CadVeiculos.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(null, " Deseja excluir o veiculo " + jtfNome.getText() + "?"  ) == JOptionPane.YES_OPTION){
            delete((( Veiculo ) Temporarios.tempObj), MemoryDataBase.listaVeiculos);
            
            if(Forms.ListVeiculos != null)
                ((ListVeiculos) Forms.ListVeiculos).listar(MemoryDataBase.listaVeiculos);
            
            Temporarios.limpar();  
            
           verifyDadosTemp();
           
           setarID();
           
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(Temporarios.tempObj == null){
            cadastrar(jtfChassi.getText(), jtfMarca.getText(), jtfNome.getText(), jtfPreco.getText().replace(",", "."), MemoryDataBase.listaVeiculos);
                
            if(Forms.ListVeiculos  != null)
                ((ListVeiculos) Forms.ListVeiculos).listar(MemoryDataBase.listaVeiculos);
            
            Temporarios.limpar();
            
            verifyDadosTemp();
        }
        else{
            alterar((Veiculo) Temporarios.tempObj, jtfChassi.getText(), jtfMarca.getText(), jtfNome.getText(), jtfPreco.getText().replace("," , "."), MemoryDataBase.listaVeiculos);
            
            if(Forms.ListVeiculos != null);
                ((ListVeiculos) Forms.ListVeiculos).listar(MemoryDataBase.listaVeiculos);
//            
//            Temporarios.limpar();
//            
//            verifyDadosTemp();
//            
//            setarID();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfChassi;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPreco;
    // End of variables declaration//GEN-END:variables
}
